categories/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.get_categories_list, name="categories_list"),

    path("add/", views.category_add, name="category_add"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pages import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path("products/", include("products.urls")),
    path("users/", include("users.urls")),
    path("pages/", include("pages.urls")),
    path("categories/", include("categories.urls")),
    path("", views.home, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

categories/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )
    name = models.CharField(max_length=30, null=False, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    # is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/%s/" % (self.slug)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name)
    #     return super().save(*args, **kwargs)

products/models.py
from django.db import models

from django.conf import settings
from categories.models import Category

# Create your models here.

LABEL_CHOICES = (
    ("P", "primary"),
    ("S", "secondary"),
)


class Product(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)

    description = models.TextField(null=True)
    # thumbnail=models.URLField()
    slug = models.SlugField(null=True, blank=True, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to="products")
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
    )
    price = models.FloatField()
    product_type = models.CharField(choices=LABEL_CHOICES, max_length=1)

    def __str__(self):
        return self.name

categories/forms.py
from django.forms import ModelForm
from .models import Category


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

categories/views.py
from django.shortcuts import render, redirect


from .models import Category
from .forms import CategoryForm
from django.contrib.auth.decorators import permission_required


def get_categories_list(request):
    categories = Category.objects.all()

    return render(
        request,
        "categories_list.html",
        context={"categories": categories},
    )


@permission_required("product.add_category", login_url="/login", raise_exception=True)
def category_add(request):
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect("categories_list")
    else:
        form = CategoryForm()
    return render(request, "add_categories.html", context={"form": form})

categories/templates/add_categories.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<form action="" method="POST">
  {% csrf_token %} {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}

categories/templates/categories_list.html
{% extends "base.html" %} {% load mptt_tags %} {% block title %}Categories {%endblock title %}
{%block content %}

<header>
  

    <div class="container-fluid  d-none d-lg-block" style="min-height: 200px ;  background-color:  rgb(252, 240, 227); border-radius: 20px;" >
 
      <div class="row py-2 px-lg-5-center" style="position: absolute;
      left: 450px;
      top: 230px;" >
        
           
        <center>
        <div class="col-lg-6 text-left mb-2 mb-lg-9" >
        
          
         
           <div class="d-inline-flex align-items-center" style="color:gray;">
            
             <small><i class="fa fa-phone-alt mr-2" ></i><h4>Categories</h4></small>
              <small class="px-3">|</small>
              <small><a  href="{% url 'home' %}" style="color: gray;"><h5>Home</h5></a></small>
            
            </div>
          
        </div>
        </center>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end" style="position: absolute;
        left: 30px;
        top: 50px;">
          {% if request.user == product.user or perms.product.add_product %}
             <small><a class="btn btn-info" href="{% url 'category_add' %}" style="background-color:bisque;color: gray;" >Add new Category</a></small>
          {%endif%}   
        </div>
      </div>
  
    </div>
  
 
</header>
<div class="list-group">
      
  
          {% recursetree categories %}
                  <!-- <li> -->
                    <a class="list-group-item list-group-item-action"  href="{% url 'product_list' %}?cat={{ node.pk }}" style="color:gray; border-color: pink;border-radius: 10px;"><b>{{ node.name }}</b><small class="text-muted"></small></small></a>
                       {% if not node.is_leaf_node %}
                           <ul class="children">
                           {{ children }}
                           </ul>
                       {% endif %}
                   <!-- </li> -->
      
                {% endrecursetree %}
             </ul>
         

</div>

{% endblock content %}